spring.application.name=karlaapi

spring.datasource.url=jdbc:postgresql://localhost:5432/db_rede_eletrica
spring.datasource.username=postgres
spring.datasource.password=141724Ka!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.mapper.accept-case-insensitive-enums=true

server.port=8081

karlaapitdd.url=http://localhost:8080

api.viacep.url=https://viacep.com.br/ws/

api.openstreetmap.url=https://nominatim.openstreetmap.org