apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: karla-devops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'karlaapi'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - karlaapi-service:8081