apiVersion: apps/v1
kind: Deployment
metadata:
  name: karlaapi
  namespace: karla-devops
spec:
  replicas: 4
  selector:
    matchLabels:
      app: karlaapi
  template:
    metadata:
      labels:
        app: karlaapi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: karlaapi
          image: karlaalmeida/karlaapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: karla-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: karla-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: karla-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: karla-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: karlaapi-service
  namespace: karla-devops
spec:
  selector:
    app: karlaapi
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort