apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: karla-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 0
            privileged: true
          command:
            - /bin/bash
            - -c
            - |
              apt-get update && \
              apt-get install -y docker.io curl && \
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
              install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
              exec /usr/bin/tini -- /usr/local/bin/jenkins.sh
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: karla-devops
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30090