apiVersion: v1
kind: Secret
metadata:
  name: karla-secret
  namespace: karla-devops
type: Opaque
stringData:
  DB_NAME: db_rede_eletrica
  DB_USER: postgres
  DB_PASSWORD: 141724Ka!
  JWT_SECRET: minha-chave-jwt-super-segura-para-devops